feat: 채팅리스트 와 채팅 페이지 로딩및 에러처리
Network-office/Network-office-FE pull request #102
Opened 2024-10-16 13:19 UTC by ienrum

# 채팅 방 및 채팅 목록 페이지에 loading 처리
## 공용 스켈레톤 컴포넌트
스켈레톤 처리에 도움이되는 선언적으로 사용가능한 skeleton 컴포넌트를 구현했습니다.

### 사용법
```ts
<SkeletonLoader className="w-1/3 h-4" />
```
![image](https://github.com/user-attachments/assets/eaf6f051-3c3a-46cc-a5f9-c36616f8d341)
![image](https://github.com/user-attachments/assets/b7b50746-f0b9-4b8a-ae07-bbdcd81dca20)

# Erroboundary 를 사용해 에러처리
장권님께서 구현해주신 ErrorBoundary 컴포넌트를 감싸 에러처리를 했습니다.
![image](https://github.com/user-attachments/assets/e929ad33-b905-4707-844f-63ebd58b1b4f)

2024-10-21 08:25 UTC, JuJangGwon requested changes
고생 많으셨습니다 수혁님!

2024-10-21 08:25 UTC, JuJangGwon commented on src/_common/_components/SkeletonLoader.tsx
> +
불필요한 import가 있는거같습니다!

2024-10-21 08:25 UTC, JuJangGwon commented on src/_common/_components/SkeletonLoader.tsx
오홍이 이때까지 일일이 만들어서 쓰고있었는데 추상화 해주셨군요! 
해당 컴포넌트도 스토리북에 추가해보는건 어떨까요?

2024-10-21 08:25 UTC, JuJangGwon commented on src/app/chat/[chatId]/layout.tsx
> +import { Suspense } from "react"
음 Suspense도 이번 컴포넌트에서 사용되지않는거같습니다 👀

2024-10-26 06:07 UTC, ienrum commented on src/_common/_components/SkeletonLoader.tsx
> +
넵 수정해보겠습니다!

2024-10-26 06:07 UTC, ienrum commented on src/_common/_components/SkeletonLoader.tsx
넵 한번 추가해볼게요~!

2024-10-26 06:08 UTC, ienrum commented on src/app/chat/[chatId]/layout.tsx
> +import { Suspense } from "react"
어 그러네요.. 수정해보겠습니다.!

2024-10-26 07:04 UTC, JuJangGwon approved these changes
고생하셨습니다!

2024-10-26 07:13 UTC, merged