feat: 카카오 로그인 연결 완료
Network-office/Network-office-FE pull request #108
Opened 2024-10-19 08:34 UTC by khj0426

카카오 로그인을 연결하였습니다.
기존 refeturn-fetch에서 x-xsrf-token이 헤더에 안 심어지는 문제가 있어서, fetch를 사용하기로 했습니다.
이 이유는 한번 깊게 파볼 생각입니다.

2024-10-20 08:45 UTC, JuJangGwon requested changes
고생많으셨습니다 효중님!

2024-10-20 08:45 UTC, JuJangGwon commented on next.config.mjs
> +  }
모킹 모드와 실제 api 사용 모드를 따로 분류하고 모드는 .env를 통해 설정하게 해두는건 어떨까요?

2024-10-20 08:45 UTC, JuJangGwon commented on src/app/api/kakao/useKakaoMutation.ts
폴더 컨벤션이 지켜지지 않은거같습니다. 페이지 폴더가 아닌 경우 `_` 언더바를 사용해서 폴더를 구분해야하며, 커스텀훅같은경우 _hooks/_quries 에 저장되어야합니다!

2024-10-20 08:45 UTC, JuJangGwon commented on src/app/kakao/login/[socialid]/page.tsx
> +  }
로그인 실패했을때, `useToast`훅을 이용해서 에러 메세지를 나타나게 하는것도 좋을거같아요!

2024-10-20 08:45 UTC, JuJangGwon commented on src/app/kakao/login/page.tsx
> +      "https://kauth.kakao.com/oauth/authorize?redirect_uri=https://localhost:3000/kakao/login&response_type=code&client_id=dda9ca07ec9d628b718b8475c11feec6"
clienID를 담고있어서 민감한 링크인거같은데 해당 링크는 .env에 상수로 저장해서 사용하는건 어떨까요

2024-10-20 10:54 UTC, YehyeokBang reviewed
구경왔습니다. csrf 관련해서 모르는 것이 있다면 질문해주세요!

2024-10-24 10:44 UTC, khj0426 commented
리뷰 모두 반영해서 머지 하겠씀당

2024-10-24 10:47 UTC, merged